//
// Created by cpasjuste on 01/01/2022.
//

#ifndef SDL2_PS4_SHADER_FRAGMENT_TEXTURE_BGR_H
#define SDL2_PS4_SHADER_FRAGMENT_TEXTURE_BGR_H

extern const char PS4_SHADER_FRAGMENT_TEXTURE_BGR[];
const int PS4_SHADER_FRAGMENT_TEXTURE_BGR_LENGTH = 784;

#endif //SDL2_PS4_SHADER_FRAGMENT_TEXTURE_BGR_H
