//
// Created by cpasjuste on 01/01/2022.
//

#ifndef SDL2_PS4_SHADER_FRAGMENT_TEXTURE_RGB_H
#define SDL2_PS4_SHADER_FRAGMENT_TEXTURE_RGB_H

extern const char PS4_SHADER_FRAGMENT_TEXTURE_RGB[];
const int PS4_SHADER_FRAGMENT_TEXTURE_RGB_LENGTH = 850;

#endif //SDL2_PS4_SHADER_FRAGMENT_TEXTURE_RGB_H
