//
// Created by cpasjuste on 01/01/2022.
//

#ifndef SDL2_PS4_SHADER_FRAGMENT_TEXTURE_NV12_JPEG_H
#define SDL2_PS4_SHADER_FRAGMENT_TEXTURE_NV12_JPEG_H

extern const char PS4_SHADER_FRAGMENT_TEXTURE_NV12_JPEG[];
const int PS4_SHADER_FRAGMENT_TEXTURE_NV12_JPEG_LENGTH = 1398;

#endif //SDL2_PS4_SHADER_FRAGMENT_TEXTURE_NV12_JPEG_H
