//
// Created by cpasjuste on 01/01/2022.
//

#ifndef SDL2_PS4_SHADER_FRAGMENT_TEXTURE_YUV_JPEG_H
#define SDL2_PS4_SHADER_FRAGMENT_TEXTURE_YUV_JPEG_H

extern const char PS4_SHADER_FRAGMENT_TEXTURE_YUV_JPEG[];
const int PS4_SHADER_FRAGMENT_TEXTURE_YUV_JPEG_LENGTH = 1514;

#endif //SDL2_PS4_SHADER_FRAGMENT_TEXTURE_YUV_JPEG_H
