name: Build (OpenWatcom)

on: [push, pull_request]

jobs:
  os2:
    name: ${{ matrix.platform.name }}
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows, makefile: Makefile.w32, artifact-name: SDL2_w32.dll }
        - { name: OS/2,    makefile: Makefile.os2, artifact-name: SDL2_os2.dll }

    steps:
      - uses: actions/checkout@v4
      - uses: open-watcom/setup-watcom@v0
      - name: Build SDL2
        run: |
          wmake -f ${{ matrix.platform.makefile }} ENABLE_WERROR=1
      - name: Build tests
        run: |
          cd test && wmake -f ${{ matrix.platform.makefile }} ENABLE_WERROR=1
          cd ..
      - name: Run tests
        if: "matrix.platform.makefile == 'Makefile.w32'"
        run: |
          cd test && wmake -f ${{ matrix.platform.makefile }} check-quick
          cd ..
      # Upload the created artifact
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          path: SDL2.dll
          name: ${{ matrix.platform.artifact-name }}
      - name: distclean
        run: |
          wmake -f ${{ matrix.platform.makefile }} distclean
          cd test && wmake -f ${{ matrix.platform.makefile }} distclean
          cd ..
